#!/command/with-contenv bashio
# shellcheck shell=bash
set -e

# Get configuration
NETWORK_KEY=$(bashio::config 'network_key')
MQTT_URL=$(bashio::config 'mqtt.url')
MQTT_USERNAME=$(bashio::config 'mqtt.username')
MQTT_PASSWORD=$(bashio::config 'mqtt.password')
MQTT_TOPIC=$(bashio::config 'mqtt.topic')
MQTT_DISCOVERY_PREFIX=$(bashio::config 'mqtt.device_discovery_prefix')
CAPTURE_SOURCE=$(bashio::config 'capture.source')
CAPTURE_INTERFACE=$(bashio::config 'capture.interface')
CAPTURE_CHANNEL=$(bashio::config 'capture.channel')
ADD_CLI_ARGS=$(bashio::config 'advanced.add_cli_args')
LOG_LEVEL=$(bashio::config 'advanced.log_level')
BUFFER_FORMAT=$(bashio::config 'advanced.buffer_format')
PUBLISH_UNKNOWN=$(bashio::config 'advanced.publish_unknown_devices')
UNWRAP_LAYERS=$(jq -c '.advanced.unwrap_layers // []' '/data/options.json')

# Validate required configuration
if [ -z "$NETWORK_KEY" ]; then
    bashio::log.error "network_key is required!"
    exit 1
fi

# Create config directory if it doesn't exist
mkdir -p /data

# Generate local_config.toml for ViLocal
bashio::log.info "Generating ViLocal configuration..."

VILOCAL_CONFIG_FILE="/app/local_config.toml"

cat > "$VILOCAL_CONFIG_FILE" <<EOF
# ViLocal configuration
# Generated by Home Assistant App

named_pipe = "/tmp/vilocal.pipe"
network_key = "$NETWORK_KEY"
log_level = "$LOG_LEVEL"
buffer_format = "$BUFFER_FORMAT"
unwrap_layers = $UNWRAP_LAYERS
publish_unknown_devices = $PUBLISH_UNKNOWN

[mqtt]
url = "$MQTT_URL"
username = "$MQTT_USERNAME"
password = "$MQTT_PASSWORD"
topic = "$MQTT_TOPIC"
device_discovery_prefix = "$MQTT_DISCOVERY_PREFIX"

EOF

normalize_entity_id() {
    local value="$1"

    # Split camelCase/PascalCase boundaries before lowercasing.
    value=$(printf '%s' "$value" | sed -E 's/([[:lower:][:digit:]])([[:upper:]])/\1_\2/g')

    # Transliterate UTF-8 names to ASCII so IDs stay HA-friendly (e.g. Gäste -> Gaste).
    if command -v iconv >/dev/null 2>&1; then
        value=$(printf '%s' "$value" | iconv -f UTF-8 -t ASCII//TRANSLIT 2>/dev/null || printf '%s' "$value")
    fi

    value=$(printf '%s' "$value" \
        | tr '[:upper:]' '[:lower:]' \
        | sed -E 's/[^a-z0-9]+/_/g; s/^_+//; s/_+$//; s/_+/_/g')

    printf '%s' "$value"
}

# Add thermostats if configured
THERMOSTATS=$(bashio::config 'thermostats')
if [ -n "$THERMOSTATS" ] && [ "$THERMOSTATS" != "[]" ]; then
    bashio::log.info "Adding thermostats configuration..."
    echo "[thermostats]" >> "$VILOCAL_CONFIG_FILE"

    # Parse thermostats array
    THERMOSTAT_COUNT=$(jq '.thermostats | length' "/data/options.json")
    for ((i=0; i<THERMOSTAT_COUNT; i++)); do
        SERIAL=$(jq -r ".thermostats[$i].serial_no" "/data/options.json")
        NAME=$(jq -r ".thermostats[$i].name" "/data/options.json")
        ENTITY_ID=$(jq -r ".thermostats[$i].entity_id // empty" "/data/options.json")
        AREA=$(jq -r ".thermostats[$i].suggested_area // empty" "/data/options.json")
        CLIMATE_SENSOR=$(jq -r ".thermostats[$i].climate_sensor_serial_no // empty" "/data/options.json")

        if [ -z "$ENTITY_ID" ]; then
            ENTITY_ID=$(normalize_entity_id "$NAME")
        fi

        THERMOSTAT_ID="$ENTITY_ID"
        if [ -z "$THERMOSTAT_ID" ]; then
            THERMOSTAT_ID="thermostat_${i}"
        fi

        echo "" >> "$VILOCAL_CONFIG_FILE"
        echo "[thermostats.${THERMOSTAT_ID}]" >> "$VILOCAL_CONFIG_FILE"
        echo "serial_no = \"$SERIAL\"" >> "$VILOCAL_CONFIG_FILE"
        echo "name = \"$NAME\"" >> "$VILOCAL_CONFIG_FILE"

        if [ -n "$AREA" ]; then
            echo "suggested_area = \"$AREA\"" >> "$VILOCAL_CONFIG_FILE"
        fi

        if [ -n "$CLIMATE_SENSOR" ]; then
            echo "climate_sensor_serial_no = \"$CLIMATE_SENSOR\"" >> "$VILOCAL_CONFIG_FILE"
        fi
    done
fi

# Add climate sensors if configured
CLIMATE_SENSORS=$(bashio::config 'climate_sensors')
if [ -n "$CLIMATE_SENSORS" ] && [ "$CLIMATE_SENSORS" != "[]" ]; then
    bashio::log.info "Adding climate sensors configuration..."
    echo "" >> "$VILOCAL_CONFIG_FILE"
    echo "[climate_sensors]" >> "$VILOCAL_CONFIG_FILE"

    # Parse climate_sensors array
    SENSOR_COUNT=$(jq '.climate_sensors | length' "/data/options.json")
    for ((i=0; i<SENSOR_COUNT; i++)); do
        SERIAL=$(jq -r ".climate_sensors[$i].serial_no" "/data/options.json")
        NAME=$(jq -r ".climate_sensors[$i].name" "/data/options.json")
        ENTITY_ID=$(jq -r ".climate_sensors[$i].entity_id // empty" "/data/options.json")
        AREA=$(jq -r ".climate_sensors[$i].suggested_area // empty" "/data/options.json")

        if [ -z "$ENTITY_ID" ]; then
            ENTITY_ID=$(normalize_entity_id "$NAME")
        fi

        SENSOR_ID="$ENTITY_ID"
        if [ -z "$SENSOR_ID" ]; then
            SENSOR_ID="sensor_${i}"
        fi

        echo "" >> "$VILOCAL_CONFIG_FILE"
        echo "[climate_sensors.${SENSOR_ID}]" >> "$VILOCAL_CONFIG_FILE"
        echo "serial_no = \"$SERIAL\"" >> "$VILOCAL_CONFIG_FILE"
        echo "name = \"$NAME\"" >> "$VILOCAL_CONFIG_FILE"

        if [ -n "$AREA" ]; then
            echo "suggested_area = \"$AREA\"" >> "$VILOCAL_CONFIG_FILE"
        fi
    done
fi

bashio::log.info "Configuration generated at $VILOCAL_CONFIG_FILE"

# Dump the configuration file for debugging (hiding secrets)
bashio::log.info "Dumping configuration file:"
sed -E \
    -e 's/(network_key[[:space:]]*=[[:space:]]*").*(")/\1****\2/' \
    -e 's/(password[[:space:]]*=[[:space:]]*").*(")/\1****\2/' \
    "$VILOCAL_CONFIG_FILE" | while read -r line; do
    bashio::log.info "$line"
done

# Start ViLocal with configured capture backend
bashio::log.info "Starting ViLocal with capture source: $CAPTURE_SOURCE"

cd /app

CAPTURE_EXTRA_ARGS=()
if [ -n "$ADD_CLI_ARGS" ] && [ "$ADD_CLI_ARGS" != "null" ]; then
    # Split extra flags by whitespace to allow optional passthrough CLI args.
    # shellcheck disable=SC2206
    CAPTURE_EXTRA_ARGS=($ADD_CLI_ARGS)
fi

log_effective_command() {
    local rendered
    printf -v rendered '%q ' "$@"
    bashio::log.info "Effective command: ${rendered% }"
}

if [ "$CAPTURE_SOURCE" = "embersniff" ]; then
    if [ -z "$CAPTURE_INTERFACE" ]; then
        bashio::log.error "capture.interface is required when using embersniff!"
        exit 1
    fi

    if [ -z "$CAPTURE_CHANNEL" ]; then
        bashio::log.error "capture.channel is required when using embersniff!"
        exit 1
    fi

    # Start ember-sniff stream and pipe to ViLocal
    bashio::log.info "Using embersniff capture interface/path: $CAPTURE_INTERFACE on channel: $CAPTURE_CHANNEL"
    log_effective_command /app/start.sh ember-sniff -p "$CAPTURE_INTERFACE" -c "$CAPTURE_CHANNEL" "${CAPTURE_EXTRA_ARGS[@]}"

    /app/start.sh ember-sniff -p "$CAPTURE_INTERFACE" -c "$CAPTURE_CHANNEL" "${CAPTURE_EXTRA_ARGS[@]}" 2>&1 &
    VILOCAL_PID=$!

    # Give it time to start
    sleep 5

    # Check if process is still running
    if ! kill -0 $VILOCAL_PID 2>/dev/null; then
        bashio::log.error "ViLocal failed to start!"
        exit 1
    fi

    # Wait for process
    wait $VILOCAL_PID

elif [ "$CAPTURE_SOURCE" = "tcpdump" ]; then
    # Use tcpdump capture (requires interface to be set)
    if [ -z "$CAPTURE_INTERFACE" ]; then
        bashio::log.error "capture.interface is required when using tcpdump!"
        exit 1
    fi

    bashio::log.info "Using tcpdump on interface: $CAPTURE_INTERFACE"
    log_effective_command /app/start.sh tcpdump -i "$CAPTURE_INTERFACE" -U -w - "${CAPTURE_EXTRA_ARGS[@]}"

    /app/start.sh tcpdump -i "$CAPTURE_INTERFACE" -U -w - "${CAPTURE_EXTRA_ARGS[@]}" 2>&1 &
    VILOCAL_PID=$!

    # Wait for process
    wait $VILOCAL_PID
elif [ "$CAPTURE_SOURCE" = "whsniff" ]; then
    if [ -z "$CAPTURE_CHANNEL" ]; then
        bashio::log.error "capture.channel is required when using whsniff!"
        exit 1
    fi

    bashio::log.info "Using whsniff on channel: $CAPTURE_CHANNEL"
    log_effective_command /app/start.sh whsniff -c "$CAPTURE_CHANNEL" "${CAPTURE_EXTRA_ARGS[@]}"

    /app/start.sh whsniff -c "$CAPTURE_CHANNEL" "${CAPTURE_EXTRA_ARGS[@]}" 2>&1 &
    VILOCAL_PID=$!

    # Wait for process
    wait $VILOCAL_PID
else
    bashio::log.error "Unknown capture source: $CAPTURE_SOURCE"
    exit 1
fi

bashio::log.error "ViLocal has exited unexpectedly!"
exit 1
